name: ci

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Download artifact
        uses: Legit-Labs/action-download-artifact@v2
        continue-on-error: true
        id: download
        with:
          repo: "iPanelDev/WebConsole"
          workflow: "deploy.yml"
          workflow_conclusion: success
          github_token: ${{ secrets.GITHUB_TOKEN }}
          event: push
          name: "github-pages"
          path: ${{ github.workspace }}
          check_artifacts: true

      - name: Extract files
        if: ${{ steps.download.outcome == 'success' }}
        continue-on-error: true
        shell: powershell
        run: |
          cd "${{ github.workspace }}"
          7z e -odist -y artifact.tar
          7z a -y dist.zip ./dist/*
          copy dist.zip src/Sources/dist.zip

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build the solution
        run: |
          dotnet restore
          dotnet build

      - name: Upload `net48`
        uses: actions/upload-artifact@v3
        with:
          name: net48
          path: ${{ github.workspace }}\src\bin\debug\net48

      - name: Upload `net6.0`
        uses: actions/upload-artifact@v3
        with:
          name: net6.0
          path: ${{ github.workspace }}\src\bin\debug\net6.0

      - name: Run tests
        run: dotnet test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Result
          path: test/TestResults/*/iPanel-Host.Tests.trx
          reporter: dotnet-trx

  Format:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install csharpier
        run: dotnet tool install csharpier -g

      - name: Format codes
        run: dotnet-csharpier .

      - uses: EndBug/add-and-commit@v9
        continue-on-error: true
        with:
          message: "style: auto format"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
